import type { NextPage } from "next";
import Head from "next/head";
import { Container } from "../components/Layout";
import { Heading, Text } from "../components/Typography";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Container
                    orientation="flex-col"
                    width="w-full"
                    height="h-screen"
                    bg="bg-gray-900"
                    justifyContent="justify-center"
                    alignItems="items-center"
                >
                    <Container
                        bg="bg-gray-800"
                        p="p-12"
                        color="text-gray-100"
                        br="rounded-xl"
                        justifyContent="justify-center"
                        gap="gap-4"
                    >
                        <Heading fontSize="text-7xl" fontWeight="font-medium">
                            Portfolio V2
                        </Heading>
                        <Text textAlign="text-center" fontSize="text-2xl">
                            Soon to come
                        </Text>
                    </Container>
                </Container>
            </main>
        </div>
    );
};

export default Home;
