import type { NextPage } from "next";
import Head from "next/head";
import DashboardNav from "../components/Dashboard/DashboardNav";
import { Container } from "../components/General";
import { Heading, Text } from "../components/General";

const Home: NextPage = () => {
    return (
        <Container h="h-screen" bg="bg-blue-100">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>
                <DashboardNav />
            </header>

            <main className="w-full h-full">
                <Container
                    flexDirection="flex-col"
                    w="w-full"
                    minH="min-h-full"
                    bg="bg-gray-900"
                    justifyContent="justify-center"
                    alignItems="items-center"
                >
                    <Container
                        bg="bg-gray-800"
                        p="p-12"
                        color="text-gray-100"
                        br="rounded-xl"
                        justifyContent="justify-center"
                        gap="gap-4"
                    >
                        <Heading fontSize="text-7xl" fontWeight="font-medium">
                            Portfolio V2
                        </Heading>
                        <Text textAlign="text-center" fontSize="text-2xl">
                            Soon to come
                        </Text>
                    </Container>
                </Container>
            </main>
        </Container>
    );
};

export default Home;
