import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import DashboardNav from "../components/Dashboard/DashboardNav";
import { Heading, Container, Button, Text } from "../components/General";

interface MessageInterface {
    _id: string;
    name: string;
    email: string;
    subject: string;
    content: string;
}

const MessagePage: NextPage = () => {
    const [messages, setMessages] = useState<MessageInterface[]>([]);
    const [loading, setLoading] = useState<boolean>(false);
    const [isError, setIsError] = useState<boolean>(false);

    const handleFetchMessages = async () => {
        console.log("started fetching");
        setLoading(true);
        setIsError(false);
        try {
            const res = await fetch("/api/messages");
            const data = await res.json();
            setMessages(data.message);
        } catch (error) {
            setIsError(true);
        }
        setLoading(false);
    };

    return (
        <Container h="h-screen" bg="bg-blue-100">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>
                <DashboardNav />
            </header>

            <main className="w-full p-6">
                <Container w="w-full" gap="gap-3">
                    <Heading>Messages</Heading>
                    <Container flexDirection="flex-row" gap="gap-3">
                        <Button onClick={handleFetchMessages}>
                            Fetch messages
                        </Button>
                        <Button onClick={() => console.log(messages)}>
                            Log messages
                        </Button>
                    </Container>
                    <Container gap="gap-6">
                        {messages.map((message: MessageInterface) => {
                            return (
                                <MessageItem
                                    key={message._id}
                                    message={message}
                                />
                            );
                        })}
                    </Container>
                </Container>
            </main>
        </Container>
    );
};

const MessageItem = ({ message }: { message: MessageInterface }) => {
    const handleDelete = async () => {
        try {
            const res = await fetch("/api/messages", {
                method: "DELETE",
                body: message._id,
            });
            const data = await res.json();
            console.log(data);
        } catch (error) {
            console.log(error);
        }
    };

    return (
        <Container
            br="rounded-xl"
            bg="bg-gray-300"
            px="px-6"
            py="py-6"
            gap="gap-6"
        >
            <Container flexDirection="flex-row" gap="gap-12">
                <Container gap="gap-0.5">
                    <Text fontWeight="font-bold">From:</Text>
                    <Text>{message.name}</Text>
                </Container>
                <Container gap="gap-0.5">
                    <Text fontWeight="font-bold">Email:</Text>
                    <Text>{message.email}</Text>
                </Container>
            </Container>
            <Container>
                <Text fontWeight="font-bold">Subject: </Text>
                <Text>{message.subject}</Text>
            </Container>
            <Container>
                <Text fontWeight="font-bold">Message: </Text>
                <Text>{message.content}</Text>
            </Container>
            <Button onClick={handleDelete}>Delete message</Button>
        </Container>
    );
};

export default MessagePage;
